In [3]:
# numpy
import numpy as np

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(np.arange(0,100,5))

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
print(np.ones((2,3,4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [18]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#random numbers b/w 0 and 1
np.random.rand(10,10)

array([[0.87939251, 0.09798103, 0.62911747, 0.08176204, 0.375743  ,
        0.45618434, 0.6424324 , 0.06392562, 0.73125887, 0.61706714],
       [0.87764566, 0.92036106, 0.09352884, 0.37566534, 0.05339156,
        0.44189828, 0.04285104, 0.22469208, 0.57659898, 0.20395973],
       [0.02420309, 0.98157892, 0.15212213, 0.63147256, 0.45103274,
        0.72619964, 0.8031876 , 0.36006667, 0.29714204, 0.25028525],
       [0.45614445, 0.76708377, 0.82219642, 0.35879241, 0.239084  ,
        0.28721279, 0.8075709 , 0.06432925, 0.09085346, 0.05807235],
       [0.6913936 , 0.11457423, 0.49584114, 0.13212812, 0.41632082,
        0.29016909, 0.63561386, 0.98840847, 0.84517423, 0.77470273],
       [0.81749031, 0.79837427, 0.46597593, 0.37517624, 0.52312998,
        0.96111614, 0.26219188, 0.58660069, 0.63799084, 0.5441961 ],
       [0.25252662, 0.95721997, 0.66460497, 0.22647348, 0.20227757,
        0.17613104, 0.02940284, 0.4463825 , 0.99056542, 0.05996267],
       [0.6883905 , 0.49225719, 0.4272046

In [20]:
#random integers
np.random.randint(1,100)

59

In [21]:
#random integers
np.random.randint(1,100,20)

array([ 5, 40, 52, 38, 76, 93, 33, 21, 96,  2,  2, 60, 39,  4, 43, 32, 59,
       67, 12, 51])

In [22]:
arr = np.random.rand(30)
randarr = np.random.randint(0,500,10)

In [27]:
arr.reshape(5,6)

array([[0.59584163, 0.31085338, 0.90275704, 0.75398047, 0.69024484,
        0.81102419],
       [0.88600355, 0.13631953, 0.23826556, 0.22515475, 0.41020373,
        0.57521752],
       [0.85655603, 0.82791631, 0.31405139, 0.57243443, 0.90905778,
        0.42138321],
       [0.77668716, 0.89188082, 0.37779293, 0.81005096, 0.79685501,
        0.41372459],
       [0.59033272, 0.64789729, 0.67716164, 0.58677206, 0.46985337,
        0.89348778]])

In [34]:
arr.reshape(6,5)
print(arr[8])

0.23826556411564104


In [36]:
arr.max()
#arr.min()

0.9090577790688197

In [38]:
arr.argmax()

16

In [39]:
arr[16]

0.9090577790688197

In [40]:
arr = arr.reshape(6,5)

In [43]:
arr.dtype

dtype('float64')

In [47]:
randarr

array([485, 267, 281,  95, 417, 487, 194,  69,  84, 445])

In [49]:
randarr[:3]

array([485, 267, 281])

In [55]:
arr[0:2,0:2]


array([[0.59584163, 0.31085338],
       [0.81102419, 0.88600355]])

In [56]:
#conditional selection 
arr = np.arange(1,11)

In [60]:
bool_arr = arr > 5

In [62]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [64]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [72]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [73]:
np.max(arr)

10

In [74]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [90]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])